# Generated by Django 4.1.3 on 2022-11-16 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_car_description_alter_car_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=300)),
                ('use', models.CharField(choices=[('P', 'Performance'), ('A', 'Aesthetic'), ('S', 'Saftey'), ('PA', 'Performance & Aesthetic'), ('PS', 'Performance & Saftey'), ('SA', 'Saftey & Aesthetic'), ('A', 'Both')], default='P', max_length=2)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
    ]
