# Generated by Django 4.1.3 on 2022-11-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_owner_car_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=200)),
                ('visits', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='owners',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.AddField(
            model_name='car',
            name='tracks',
            field=models.ManyToManyField(to='main_app.track'),
        ),
    ]
