# Generated by Django 4.1.3 on 2022-11-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_track_remove_car_owners_delete_owner_car_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='visits',
        ),
        migrations.AddField(
            model_name='track',
            name='location',
            field=models.CharField(default='USA', max_length=500),
        ),
    ]
